language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
script: 
  - mvn clean verify
  - mvn checkstyle:checkstyle

services:
- mysql

before_script:
  - mysql -e 'create database giftit;'


