FROM ubuntu:latest

#pretty much works, but this approach is ugly. Doesn't like it. to start tomcat you have to connect to the container and
#run 'service tomcat7 start' it will say that failed, but don't believe it.
#to make this work rename startup.sh.old to startup.sh

RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get -y update
# Accept the license
RUN echo "oracle-java7-installer shared/accepted-oracle-license-v1-1 boolean true" | debconf-set-selections

RUN apt-get -y install oracle-java8-installer

# Here comes the tomcat installation
RUN apt-get -y install tomcat7
RUN echo "JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> /etc/default/tomcat7

# Expose the default tomcat port
EXPOSE 8080


RUN apt-get install maven -y
RUN apt-get install git -y


RUN DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server \
    &&  service mysql start \
    &&  mysqladmin -u root password root

ADD pom.xml /app/
ADD src/ /app/src
ADD table.sql /opt/table.sql
WORKDIR /app/
ADD startup.sh /opt/startup.sh
RUN chmod 777 /opt/startup.sh
RUN /opt/startup.sh
ENTRYPOINT ["sh"]
#ENTRYPOINT ["sh"]